package rules_test

import (
	"context"
	"errors"
	"strings"
	"testing"

	"league_app/backend/domainerr"
	"league_app/backend/domains/rules"
	"league_app/models"
)

// stubRuleStore is a minimal in-memory RuleStore for service tests.
type stubRuleStore struct {
	rows   []models.SeasonRule
	nextID int64
	getErr error // force GetByID to return this error
}

func newStub(initial ...models.SeasonRule) *stubRuleStore {
	s := &stubRuleStore{nextID: 1}
	s.rows = append(s.rows, initial...)
	if len(initial) > 0 {
		s.nextID = initial[len(initial)-1].ID + 1
	}
	return s
}

func (s *stubRuleStore) ListBySeasonID(_ context.Context, seasonID int64) ([]models.SeasonRule, error) {
	var out []models.SeasonRule
	for _, r := range s.rows {
		if r.SeasonID == seasonID {
			out = append(out, r)
		}
	}
	if out == nil {
		out = []models.SeasonRule{}
	}
	return out, nil
}

func (s *stubRuleStore) Upsert(_ context.Context, rule models.SeasonRule) (models.SeasonRule, error) {
	for i, r := range s.rows {
		if r.SeasonID == rule.SeasonID && r.RuleKey == rule.RuleKey {
			s.rows[i].RuleLabel = rule.RuleLabel
			s.rows[i].RuleValue = rule.RuleValue
			return s.rows[i], nil
		}
	}
	rule.ID = s.nextID
	s.nextID++
	s.rows = append(s.rows, rule)
	return rule, nil
}

func (s *stubRuleStore) GetByID(_ context.Context, ruleID int64) (models.SeasonRule, error) {
	if s.getErr != nil {
		return models.SeasonRule{}, s.getErr
	}
	for _, r := range s.rows {
		if r.ID == ruleID {
			return r, nil
		}
	}
	return models.SeasonRule{}, domainerr.New("RULE_NOT_FOUND", domainerr.NotFound, "rule not found")
}

func (s *stubRuleStore) UpdateByID(_ context.Context, ruleID int64, label, value string) error {
	for i, r := range s.rows {
		if r.ID == ruleID {
			s.rows[i].RuleLabel = label
			s.rows[i].RuleValue = value
			return nil
		}
	}
	return nil
}

func (s *stubRuleStore) DeleteByID(_ context.Context, ruleID int64) error {
	for i, r := range s.rows {
		if r.ID == ruleID {
			s.rows = append(s.rows[:i], s.rows[i+1:]...)
			return nil
		}
	}
	return nil
}

func (s *stubRuleStore) GetValue(_ context.Context, seasonID int64, key string) (string, bool, error) {
	for _, r := range s.rows {
		if r.SeasonID == seasonID && r.RuleKey == key {
			return r.RuleValue, true, nil
		}
	}
	return "", false, nil
}

// --- Upsert ---

func TestRuleService_Upsert_AutogeneratesKeyWhenBlank(t *testing.T) {
	svc := rules.NewRuleService(newStub())
	saved, err := svc.Upsert(context.Background(), models.SeasonRule{
		SeasonID: 1, RuleKey: "", RuleLabel: "Custom", RuleValue: "anything",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.HasPrefix(saved.RuleKey, "rule_") {
		t.Errorf("want autogenerated key with rule_ prefix, got %q", saved.RuleKey)
	}
}

func TestRuleService_Upsert_RejectsInvalidValue(t *testing.T) {
	svc := rules.NewRuleService(newStub())
	_, err := svc.Upsert(context.Background(), models.SeasonRule{
		SeasonID: 1, RuleKey: "allow_substitutes", RuleLabel: "Subs", RuleValue: "maybe",
	})
	if err == nil {
		t.Fatal("want error for invalid boolean value, got nil")
	}
	var de *domainerr.Err
	if !errors.As(err, &de) || de.Category != domainerr.InvalidInput {
		t.Errorf("want InvalidInput domainerr, got %v", err)
	}
}

func TestRuleService_Upsert_AcceptsUnknownKey(t *testing.T) {
	svc := rules.NewRuleService(newStub())
	_, err := svc.Upsert(context.Background(), models.SeasonRule{
		SeasonID: 1, RuleKey: "custom_house_rule", RuleLabel: "House Rule", RuleValue: "anything goes",
	})
	if err != nil {
		t.Errorf("unknown key should pass validation, got: %v", err)
	}
}

func TestRuleService_Upsert_ReplacesExistingKey(t *testing.T) {
	stub := newStub(models.SeasonRule{ID: 1, SeasonID: 1, RuleKey: "allow_substitutes", RuleValue: "true"})
	svc := rules.NewRuleService(stub)
	_, err := svc.Upsert(context.Background(), models.SeasonRule{
		SeasonID: 1, RuleKey: "allow_substitutes", RuleLabel: "Subs", RuleValue: "false",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if stub.rows[0].RuleValue != "false" {
		t.Errorf("want RuleValue=false after upsert, got %q", stub.rows[0].RuleValue)
	}
}

// --- Update ---

func TestRuleService_Update_ReturnsNotFoundWhenIDMissing(t *testing.T) {
	svc := rules.NewRuleService(newStub())
	err := svc.Update(context.Background(), 999, "Label", "true")
	if err == nil {
		t.Fatal("want error for missing rule, got nil")
	}
	var de *domainerr.Err
	if !errors.As(err, &de) || de.Category != domainerr.NotFound {
		t.Errorf("want NotFound domainerr, got %v", err)
	}
}

func TestRuleService_Update_RejectsInvalidValue(t *testing.T) {
	stub := newStub(models.SeasonRule{ID: 1, SeasonID: 1, RuleKey: "allow_substitutes", RuleValue: "true"})
	svc := rules.NewRuleService(stub)
	err := svc.Update(context.Background(), 1, "Subs", "maybe")
	if err == nil {
		t.Fatal("want error for invalid value, got nil")
	}
	var de *domainerr.Err
	if !errors.As(err, &de) || de.Category != domainerr.InvalidInput {
		t.Errorf("want InvalidInput domainerr, got %v", err)
	}
}

func TestRuleService_Update_WritesValidValue(t *testing.T) {
	stub := newStub(models.SeasonRule{ID: 1, SeasonID: 1, RuleKey: "allow_substitutes", RuleValue: "true"})
	svc := rules.NewRuleService(stub)
	err := svc.Update(context.Background(), 1, "Subs", "false")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if stub.rows[0].RuleValue != "false" {
		t.Errorf("want RuleValue=false after update, got %q", stub.rows[0].RuleValue)
	}
}

func TestRuleService_Update_PropagatesStoreGetError(t *testing.T) {
	stub := newStub()
	stub.getErr = errors.New("db failure")
	svc := rules.NewRuleService(stub)
	err := svc.Update(context.Background(), 1, "Label", "true")
	if err == nil || !strings.Contains(err.Error(), "db failure") {
		t.Errorf("want db failure error propagated, got %v", err)
	}
}

// --- Delete ---

func TestRuleService_Delete_DelegatesToStore(t *testing.T) {
	stub := newStub(models.SeasonRule{ID: 1, SeasonID: 1, RuleKey: "allow_substitutes", RuleValue: "true"})
	svc := rules.NewRuleService(stub)
	if err := svc.Delete(context.Background(), 1); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(stub.rows) != 0 {
		t.Error("want row removed after delete")
	}
}

// --- List ---

func TestRuleService_List_DelegatesToStore(t *testing.T) {
	stub := newStub(
		models.SeasonRule{ID: 1, SeasonID: 1, RuleKey: "allow_substitutes", RuleValue: "true"},
		models.SeasonRule{ID: 2, SeasonID: 1, RuleKey: "games_per_pairing", RuleValue: "3"},
	)
	svc := rules.NewRuleService(stub)
	rows, err := svc.List(context.Background(), 1)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(rows) != 2 {
		t.Errorf("want 2 rows, got %d", len(rows))
	}
}
